services:
  backend-api:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./server/backend-api:/app

  ml-service:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001

  frontend:
    command: npm run dev -- --host
